/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * The Dash Backend
 * The Dash Backend API
 * OpenAPI spec version: 0.0.1
 */
import type { Get200ItemItemCustomFieldsAnyOf } from "./get200ItemItemCustomFieldsAnyOf";
import type { Get200ItemItemCustomFieldsAnyOfTwo } from "./get200ItemItemCustomFieldsAnyOfTwo";

export type Get200ItemItemCustomFields =
  | Get200ItemItemCustomFieldsAnyOf
  | unknown[]
  | Get200ItemItemCustomFieldsAnyOfTwo;
