/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * The Dash Backend
 * The Dash Backend API
 * OpenAPI spec version: 0.0.1
 */
import type { Get200ItemItemAddressesItem } from "./get200ItemItemAddressesItem";
import type { Get200ItemItemCustomFields } from "./get200ItemItemCustomFields";

export type Get200ItemItem = {
  addresses: Get200ItemItemAddressesItem[];
  customFields: Get200ItemItemCustomFields;
  dateOfBirth: string;
  firstName: string;
  lastName: string;
  middleName?: string;
  status: string;
};
