/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * The Dash Backend
 * The Dash Backend API
 * OpenAPI spec version: 0.0.1
 */
import type { GetGetPatients200ItemItemAddressesItem } from "./getGetPatients200ItemItemAddressesItem";
import type { GetGetPatients200ItemItemCustomFields } from "./getGetPatients200ItemItemCustomFields";

export type GetGetPatients200ItemItem = {
  addresses: GetGetPatients200ItemItemAddressesItem[];
  customFields: GetGetPatients200ItemItemCustomFields;
  dateOfBirth: string;
  firstName: string;
  lastName: string;
  middleName?: string;
  status: string;
};
