/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * The Dash Backend
 * The Dash Backend API
 * OpenAPI spec version: 0.0.1
 */
import type { GetGetPatients200ItemItemCustomFieldsAnyOf } from "./getGetPatients200ItemItemCustomFieldsAnyOf";
import type { GetGetPatients200ItemItemCustomFieldsAnyOfTwo } from "./getGetPatients200ItemItemCustomFieldsAnyOfTwo";

export type GetGetPatients200ItemItemCustomFields =
  | GetGetPatients200ItemItemCustomFieldsAnyOf
  | unknown[]
  | GetGetPatients200ItemItemCustomFieldsAnyOfTwo;
