/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * The Dash Backend
 * The Dash Backend API
 * OpenAPI spec version: 0.0.1
 */
import type { GetGetPatients200ItemPatientCustomFieldsItemCustomField } from "./getGetPatients200ItemPatientCustomFieldsItemCustomField";

export type GetGetPatients200ItemPatientCustomFieldsItem = {
  customField: GetGetPatients200ItemPatientCustomFieldsItemCustomField;
  value: string;
};
