/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * The Dash Backend
 * The Dash Backend API
 * OpenAPI spec version: 0.0.1
 */
import type { GetGetPatients200CustomFieldsItem } from "./getGetPatients200CustomFieldsItem";
import type { GetGetPatients200PatientsItem } from "./getGetPatients200PatientsItem";

export type GetGetPatients200 = {
  customFields: GetGetPatients200CustomFieldsItem[];
  patients: GetGetPatients200PatientsItem[];
};
