/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * The Dash Backend
 * The Dash Backend API
 * OpenAPI spec version: 0.0.1
 */
import type { GetGetPatients200PatientsItemAddressesItem } from "./getGetPatients200PatientsItemAddressesItem";
import type { GetGetPatients200PatientsItemPatientCustomFieldsItem } from "./getGetPatients200PatientsItemPatientCustomFieldsItem";

export type GetGetPatients200PatientsItem = {
  addresses: GetGetPatients200PatientsItemAddressesItem[];
  dateOfBirth: string;
  firstName: string;
  id: string;
  lastName: string;
  middleName?: string;
  patientCustomFields: GetGetPatients200PatientsItemPatientCustomFieldsItem[];
  status: string;
};
