/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * The Dash Backend
 * The Dash Backend API
 * OpenAPI spec version: 0.0.1
 */

export type GetGetPatients200ItemAddressesItem = {
  city: string;
  id: string;
  state: string;
  street: string;
  zip: string;
};
