/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * The Dash Backend
 * The Dash Backend API
 * OpenAPI spec version: 0.0.1
 */
import type { PostAddPatientBodyAddressesItem } from "./postAddPatientBodyAddressesItem";
import type { PostAddPatientBodyCustomFieldsItem } from "./postAddPatientBodyCustomFieldsItem";

export type PostAddPatientBody = {
  addresses: PostAddPatientBodyAddressesItem[];
  customFields?: PostAddPatientBodyCustomFieldsItem[];
  dateOfBirth: string;
  firstName: string;
  lastName: string;
  middleName?: string;
  status: string;
};
