/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * The Dash Backend
 * The Dash Backend API
 * OpenAPI spec version: 0.0.1
 */
import type { PostAddPatientBodyCustomFieldsAnyOf } from "./postAddPatientBodyCustomFieldsAnyOf";
import type { PostAddPatientBodyCustomFieldsAnyOfTwo } from "./postAddPatientBodyCustomFieldsAnyOfTwo";

export type PostAddPatientBodyCustomFields =
  | PostAddPatientBodyCustomFieldsAnyOf
  | unknown[]
  | PostAddPatientBodyCustomFieldsAnyOfTwo;
