/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * The Dash Backend
 * The Dash Backend API
 * OpenAPI spec version: 0.0.1
 */
import type { PutBodyAddressesItem } from "./putBodyAddressesItem";
import type { PutBodyCustomFields } from "./putBodyCustomFields";

export type PutBody = {
  addresses?: PutBodyAddressesItem[];
  customFields?: PutBodyCustomFields;
  dateOfBirth?: string;
  firstName?: string;
  id?: string;
  lastName?: string;
  middleName?: string;
  status?: string;
};
