/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * The Dash Backend
 * The Dash Backend API
 * OpenAPI spec version: 0.0.1
 */

export type PutUpdatePatientBodyCustomFieldsAnyOfTwo = {
  [key: string]: unknown;
};
