/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * The Dash Backend
 * The Dash Backend API
 * OpenAPI spec version: 0.0.1
 */
import type { PutUpdatePatientBodyAddressesItem } from "./putUpdatePatientBodyAddressesItem";
import type { PutUpdatePatientBodyCustomFieldsItem } from "./putUpdatePatientBodyCustomFieldsItem";

export type PutUpdatePatientBody = {
  addresses?: PutUpdatePatientBodyAddressesItem[];
  customFields?: PutUpdatePatientBodyCustomFieldsItem[];
  dateOfBirth?: string;
  firstName?: string;
  id?: string;
  lastName?: string;
  middleName?: string;
  status?: string;
};
